# Generated by Django 4.2.1 on 2023-07-14 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='supervisior',
        ),
        migrations.AddField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Executor', 'Executor'), ('Senior Executor', 'Senior Executor'), ('Coordinator', 'Coordinator'), ('Project Manager', 'Project Manager'), ('Department Head', 'Department Head'), ('Director', 'Director'), ('CEO', 'CEO')], max_length=100),
        ),
    ]
